'use strict';
const $=id=>document.getElementById(id);
const state={place:null,saved:[],generation:0};
try{const ids=JSON.parse(localStorage.getItem('berlinbite.ids')||'[]');if(Array.isArray(ids))state.saved=ids.filter(x=>typeof x==='string'&&/^[A-Za-z0-9_-]{5,200}$/.test(x)).slice(0,30);}catch{}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function safeLink(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null;}catch{return null;}}
async function api(path,options){const r=await fetch(path,options);let data;try{data=await r.json();}catch{throw Error('The service could not respond. Please try again.');}if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Please check your input and try again.');return data;}
function view(name){for(const n of ['search','detail','saved'])$(n+'-view').hidden=n!==name;}
function count(){$('saved-count').textContent=state.saved.length;}
function persist(){try{localStorage.setItem('berlinbite.ids',JSON.stringify(state.saved));return true;}catch{$('detail-status').textContent='Your browser could not save this list. Storage may be disabled.';return false;}}
function attribution(parent,p){const a=node('div','Google Maps','attribution');a.setAttribute('translate','no');parent.append(a);for(const item of p.attributions||[]){const url=safeLink(item.providerUri);const el=node(url?'a':'span',item.provider||'Data provider');if(url){el.href=url;el.target='_blank';el.rel='noopener noreferrer';}parent.append(el);}}
function result(p){const card=node('button',undefined,'result');card.type='button';card.append(node('strong',p.name),node('small',p.address),node('span','Take a closer look ↗','go'));card.addEventListener('click',()=>select(p.id));return card;}
async function search(query){view('search');const g=++state.generation;$('search-button').disabled=true;$('search-status').textContent='Finding your next bite…';$('search-status').classList.add('loading');$('results').replaceChildren();try{const data=await api('/api/search?q='+encodeURIComponent(query));if(g!==state.generation)return;$('search-status').textContent=data.places.length?'Pick your place. We’ll take it from here.':'No matching restaurants found. Try another name or craving.';for(const p of data.places){const wrap=node('div');wrap.append(result(p));attribution(wrap,p);$('results').append(wrap);}}catch(e){if(g===state.generation)$('search-status').textContent=e.message;}finally{$('search-button').disabled=false;$('search-status').classList.remove('loading');}}
$('search-form').addEventListener('submit',e=>{e.preventDefault();search($('query').value.trim());});
for(const btn of document.querySelectorAll('[data-query]'))btn.addEventListener('click',()=>{$('query').value=btn.dataset.query;search(btn.dataset.query);});
function berlinInput(date){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date);return parts.replace(' ','T');}
// Interpret the chosen wall-clock time in Berlin, independently of the user's device timezone.
function berlinISO(value){const target=Date.parse(value+'Z');let guess=target;for(let i=0;i<3;i++){const shown=Date.parse(berlinInput(new Date(guess))+'Z');guess+=target-shown;}if(berlinInput(new Date(guess))!==value)throw Error('That time does not exist during the daylight-saving change. Choose another time.');return new Date(guess).toISOString();}
async function select(id){view('detail');state.place=null;$('detail-status').textContent='Opening this place…';$('place-name').textContent='One little moment…';$('place-address').textContent='';$('place-meta').replaceChildren();$('hours').replaceChildren();$('provider-attributions').replaceChildren();$('insights').hidden=true;$('save-button').disabled=true;$('insight-button').disabled=true;$('maps-link').hidden=true;$('website-link').hidden=true;try{const p=await api('/api/places/'+encodeURIComponent(id));state.place=p;$('place-name').textContent=p.name;$('place-address').textContent=p.address;for(const t of [p.rating!=null?'★ '+p.rating+' ('+(p.rating_count||0)+' ratings)':null,p.open_now===true?'Open now':p.open_now===false?'Closed now':'Opening status unavailable'])if(t)$('place-meta').append(node('span',t,'pill'));if(p.business_status&&p.business_status!=='OPERATIONAL')$('place-meta').append(node('span',p.business_status.replaceAll('_',' '),'pill'));const link=safeLink(p.maps_url);if(link){$('maps-link').href=link;$('maps-link').hidden=false;}const website=safeLink(p.website);if(website){$('website-link').href=website;$('website-link').hidden=false;}for(const a of p.attributions||[]){const el=node('span',a.provider||'');$('provider-attributions').append(el);}if(p.hours.length){const d=node('details'),s=node('summary','Opening hours');d.append(s);for(const h of p.hours)d.append(node('div',h,'hours'));$('hours').append(d);}$('visit-time').value=berlinInput(new Date(Date.now()+3600000));$('visit-time').min=berlinInput(new Date());$('visit-time').max=berlinInput(new Date(Date.now()+7*86400000));$('detail-status').textContent='';$('save-button').disabled=false;$('insight-button').disabled=false;saveLabel();$('detail-view').focus();}catch(e){$('detail-status').textContent=e.message;$('place-name').textContent='Couldn’t open this place';}}
function card(title,heading,body,cls=''){const e=node('article',undefined,'insight-card '+cls);e.append(node('h4',title),node('strong',heading),node('p',body));return e;}
$('insight-button').addEventListener('click',async()=>{if(!state.place)return;const id=state.place.id;$('insight-button').disabled=true;$('detail-status').textContent='Putting your evening together…';$('insights').hidden=true;try{const data=await api('/api/insight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({place_id:id,visit_at:berlinISO($('visit-time').value)})});if(state.place?.id!==id)return;const c=$('cards');c.replaceChildren();c.append(card('◷ Crowd estimate',data.crowd.label,data.crowd.basis.join(' · ')+'. '+data.crowd.disclaimer));const summary=card('✎ Quick take',data.place.summary?'About this place':'No summary available',data.place.summary||'Google Maps did not provide an editorial summary for this restaurant.');if(data.place.summary)attribution(summary,data.place);c.append(summary,card('☏ English friendliness','Ask the restaurant',data.english),card('♡ Reservations','Check ahead',data.reservation));const restaurantSite=safeLink(data.place.website);if(restaurantSite){for(const panel of [...c.children].slice(-2)){const a=node('a','Visit restaurant website ↗');a.href=restaurantSite;a.target='_blank';a.rel='noopener noreferrer';panel.append(a);}}if(data.weather)c.append(card('☀ Berlin right now',data.weather.temperature_2m+'°C',data.weather.precipitation+' mm precipitation. Current weather, not a forecast for your visit. Source: Open-Meteo.'));c.append(card('✦ Our take','Make a little plan.',data.advice+' '+data.advice_source+'.','take'));[...c.children].forEach((el,i)=>el.style.animationDelay=i*70+'ms');$('insights').hidden=false;$('detail-status').textContent='';}catch(e){$('detail-status').textContent=e.message;}finally{$('insight-button').disabled=false;}});
function saveLabel(){$('save-button').textContent=state.saved.includes(state.place?.id)?'♥ Saved to my list':'♡ Add to my list';}
$('save-button').addEventListener('click',()=>{const id=state.place?.id;if(!id)return;const before=[...state.saved];if(state.saved.includes(id))state.saved=state.saved.filter(x=>x!==id);else if(state.saved.length<30)state.saved.push(id);else{$('detail-status').textContent='Your list holds 30 places. Remove one to add another.';return;}if(!persist())state.saved=before;count();saveLabel();});
$('back').addEventListener('click',()=>view('search'));$('saved-back').addEventListener('click',()=>view('search'));
$('saved-toggle').addEventListener('click',()=>{view('saved');$('saved-items').replaceChildren();$('saved-status').textContent=state.saved.length?'Open a saved place to fetch its current details.':'Your next favourite is waiting. Search for a place and tap the heart.';state.saved.forEach((id,i)=>{const wrap=node('div',undefined,'result');const b=node('button','Saved place '+(i+1)+' ↗','text-button');b.addEventListener('click',()=>select(id));const remove=node('button','Remove','remove');remove.addEventListener('click',()=>{state.saved=state.saved.filter(x=>x!==id);persist();count();wrap.remove();});wrap.append(b,remove);$('saved-items').append(wrap);});});
count();api('/api/config').then(c=>{if(!c.places_ready){$('setup-message').hidden=false;$('setup-message').textContent='Live search is waiting for its connection. Add the Google Places key on the server to start finding real restaurants.';}}).catch(()=>{$('setup-message').hidden=false;$('setup-message').textContent='The search service is not running yet. Please try again shortly.';});
